spring.application.name=ecommerce-cloud

#Configuracao com a base de dados mysql
spring.datasource.url=jdbc:mysql://REDACTED_MYSQL_URL
spring.datasource.username=mateuscarestiato
spring.datasource.password=REDACTED_PASSWORD
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Configuracao do Cosmos DB
azure.cosmos.uri=https://REDACTED_COSMOS_URI
azure.cosmos.key=REDACTED_COSMOS_KEY
azure.cosmos.database=REDACTED_COSMOS_DB
azure.cosmos.queryMetricsEnabled=true
azure.cosmos.responseDiagnosticsEnabled=true

server.port=8081
server.address=0.0.0.0
